# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ttt.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(923, 600)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(820, 560, 81, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 881, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.task = QtWidgets.QWidget()
        self.task.setObjectName("task")
        self.label = QtWidgets.QLabel(self.task)
        self.label.setGeometry(QtCore.QRect(30, 10, 831, 481))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Pictures/Screenshot from 2024-03-07 22-28-42.png"))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.task)
        self.listWidget.setGeometry(QtCore.QRect(570, 250, 251, 211))
        self.listWidget.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.task)
        self.lineEdit.setGeometry(QtCore.QRect(50, 340, 241, 21))
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.task)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.task)
        self.lcdNumber.setGeometry(QtCore.QRect(570, 220, 64, 23))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber.setObjectName("lcdNumber")
        self.tabWidget.addTab(self.task, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 831, 481))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/Pictures/Screenshot from 2024-03-08 16-18-32.png"))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 130, 241, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(50, 220, 241, 231))
        self.listWidget_2.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(140, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_3.setGeometry(QtCore.QRect(390, 220, 251, 231))
        self.listWidget_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.listWidget_3.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(440, 180, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(50, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.Reminders = QtWidgets.QWidget()
        self.Reminders.setObjectName("Reminders")
        self.label_6 = QtWidgets.QLabel(self.Reminders)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 831, 481))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/Pictures/Screenshot from 2024-03-07 23-29-27.png"))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.Reminders)
        self.label_8.setGeometry(QtCore.QRect(50, 55, 271, 40))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.Reminders)
        self.calendarWidget.setGeometry(QtCore.QRect(330, 30, 511, 341))
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setObjectName("calendarWidget")
        self.tabWidget.addTab(self.Reminders, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Task"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task), _translate("Dialog", "Task"))
        self.label_4.setText(_translate("Dialog", "Visited"))
        self.label_5.setText(_translate("Dialog", "To be Visited"))
        self.label_7.setText(_translate("Dialog", "Travel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Travel"))
        self.label_8.setText(_translate("Dialog", "Reminders"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Reminders), _translate("Dialog", "Reminders"))
import test_rc
